debugWebModule:
  security:
    password: foobar

spring:
  datasource:
    url: jdbc:h2:./db/oauth2-module
    username: sa

adminWebModule:
  login:
    rememberMe:
      key: remember-oauth-module

acrossModule:
  OAuth2Module:
    resources: oauth2-module/src/main/resources

oauth2Module:
  use-jdbc-authorization-code-services: true