msad:
  settings:
    ldapUserObjectClass: user
    ldapUserObjectFilter: (&(objectCategory=Person)(sAMAccountName=*))
    ldapUserObjectFilterForUser: (&(objectCategory=Person)(sAMAccountName={0}))
    ldapUsername: sAMAccountName
    ldapUserEmail: mail
    ldapUserFirstName: givenName
    ldapUserLastName: sn
    ldapUserDisplayName: displayName
    ldapUserPassword: unicodePwd
    ldapGroupObjectClass: group
    ldapGroupObjectFilter: (objectCategory=Group)
    ldapGroupName: cn
    ldapGroupUsernames: member
    ldapUserGroup: memberOf
apache15:
  settings:
    ldapUserObjectClass: inetorgperson
    ldapUserObjectFilter: (objectclass=inetorgperson)
    ldapUserObjectFilterForUser: (&(objectclass=inetorgperson)(cn={0}))
    ldapUsername: cn
    ldapUserEmail: mail
    ldapUserFirstName: givenName
    ldapUserLastName: sn
    ldapUserDisplayName: displayName
    ldapUserPassword: userpassword
    ldapGroupObjectClass: groupOfUniqueNames
    ldapGroupObjectFilter: (objectclass=groupOfUniqueNames)
    ldapGroupName: cn
    ldapGroupUsernames: uniqueMember
    ldapUserGroup: memberOf
opends:
  settings:
    ldapUserObjectClass: inetorgperson
    ldapUserObjectFilter: (objectclass=inetorgperson)
    ldapUserObjectFilterForUser: (&(objectclass=inetorgperson)(uid={0}))
    ldapUsername: uid
    ldapUserEmail: mail
    ldapUserFirstName: givenName
    ldapUserLastName: sn
    ldapUserDisplayName: cn
    ldapUserPassword: userpassword
    ldapGroupObjectClass: groupOfUniqueNames
    ldapGroupObjectFilter: (objectclass=groupOfUniqueNames)
    ldapGroupName: cn
    ldapGroupUsernames: uniqueMember
    ldapUserGroup: uniqueMember