spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:../local-data/db/user-module
    username: sa

across:
  development:
    active: true

adminWebModule:
  title: UserModule
  login:
    rememberMe:
      key: user-module

server:
  port: 8080
  error:
    whitelabel:
      enabled: false
    include-stacktrace: always
security:
  basic:
    enabled: false

acrossModule:
  UserModule:
    resources:
      ../user-module/src/main/resources