across:
  development:
    active: true

acrossHibernate:
  hibernate-properties:
    hibernate.format_sql: false
    hibernate.use_sql_comments: false
    hibernate.show_sql: false
    hbm2dll.auto: create-update

adminWebModule:
  login:
    rememberMe:
      key: test-admin-ui
  root-path: /
  title: ACL Admin UI

spring:
  datasource:
    url: "jdbc:h2:./local-data/db/test-admin-ui"
    username: sa